name: Cypress - Integration Tests PR

on: [pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          record: true
          config-file: cypress.json
          start: npm run-script start:ci
          wait-on: "http://localhost:1337"
